### ISSUE TITLE
Testing the applet on Linux with a virtual reader

### ISSUE THREAD

**Issue by mgramigna** [arekinath/PivApplet#12]
@arekinath In a [previous issue](https://github.com/arekinath/PivApplet/issues/5#issuecomment-419750505), you mentioned the following:

> I've just been testing this applet on Linux in a virtual reader with my fork of jcardsim (I added support for vsmartcard/vpcd protocol over TCP rather than using BixVReader) and it seems to work ok. I did have to fix up a few little things with some lengths in jcardsim (still working out why). yubico-piv-tool seems to talk to it fine though.

Is there any more detail you can give related to how you set up your testing? What the length issues were that you had to fix, how you setup TCP, etc.

**Comment by arekinath** [comment]
I put some notes about it on the README: https://github.com/arekinath/PivApplet#simulation

The patch I'm using with jcardsim is here: https://github.com/arekinath/jcardsim/commit/5389ece6528138c7b20dbaa5594f688293f8a01f

**Comment by mgramigna** [comment]
Awesome. Those notes were super helpful. We were able to get it working. Thanks!

**Comment by mgramigna** [comment]
By the way, I think one of the commands on the README should be updated. We got an exception when running `java -noverify -cp bin/:../jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard test/jcardsim.cfg` because we also had to specify the src directory of the piv applet.

The command that worked for us was `java -noverify -cp ./src/:bin/:../jcardsim/target/jcardsim-3.0.5-SNAPSHOT.jar com.licel.jcardsim.remote.VSmartCard test/jcardsim.cfg`
