### ISSUE TITLE
Unable to import pfx in YubiKey PIV manager

### ISSUE THREAD

**Issue by kategray** [arekinath/PivApplet#16]
I am unable to import a .pfx file using the latest released .cap and the YubiKey PIV Manager GUI.

The card is successfully detected, and I am prompted to perform device initialization.  I select to use the PIN as management key.  Once that finishes, I go to Certificates, Authentication, and attempt to import a .pfx file.

This gets me the error:

"Error: Failed to load PKCS12 from file.  Unable to import private key"

As a test, I generated a new .pfx from scratch using the following commands:

```
openssl req -new -keyout cert.key -nodes -outform PEM > cert.csr
openssl x509 -in cert.csr -out cert.pem -req -signkey key.pem -days 1001
openssl pkcs12 -export -out cert.pfx -inkey cert.key -in cert.pem -password pass:test
```

Import still fails.

**Comment by kategray** [comment]
Additionally, if I re-open the management app, and attempt to load, it will prompt for the PIN and then the Management key.

I'm wondering if the key derivation for the management key is failing some how.

**Comment by kategray** [comment]
Forcibly setting the management key to "010203040506070801020304050607080102030405060708" does not seem to help.

**Comment by kategray** [comment]
Importing using the command line app seems to work fine (test cert, no confidential information in this).

```
C:\Kate\JavaCard\PivApplet>"C:\Program Files (x86)\Yubico\YubiKey PIV Manager\yubico-piv-tool" -v9 -r "ACS ACR33U-A1 3SAM ICC Reader ICC 0" -s9a -KPKCS12 -icert\cert.pfx -aimport-key -aimport-certificate
trying to connect to reader 'ACS ACR33U-A1 3SAM ICC Reader ICC 0'.
> 00 a4 04 00 08 a0 00 00 05 27 20 01 01
< 6a 82
Failed selecting yk application: 6a82
> 00 a4 04 00 05 a0 00 00 03 08
< 61 3d 4f 0b a0 00 00 03 08 00 00 10 00 01 00 79 0d 4f 0b a0 00 00 03 08 00 00 10 00 01 00 50 09 50 69 76 41 70 70 6c 65 74 ac 14 80 01 03 80 01 06 80 01 07 80 01 11 80 01 f0 80 01 f1 06 00 90 00
> 00 fd 00 00 00
< 05 00 00 90 00
Asking for password since 'import-key' needs it.
Enter Password:
Authenticating since action 'import-key' needs that.
> 00 87 03 9b 04 7c 02 80 00
< 7c 0a 80 08 74 37 d1 28 97 61 87 18 90 00
> 00 87 03 9b 16 7c 14 80 08 ba c4 c3 46 0f 21 23 d0 81 08 2b 20 93 5b 23 14 b1 d8
< 7c 0a 82 08 d0 2d 70 c2 95 81 50 81 90 00
Successful application authentication.
Skipping authentication for 'import-certificate' since it's already done.
Now processing for action 'import-key'.
Going to send 255 bytes in this go.
> 10 fe 07 9a ff 01 81 80 ed 96 b6 a8 81 15 da b6 62 1d a7 e9 70 a0 b6 8e cc 30 4b a1 f3 14 70 0e c4 d3 d7 78 cf ff fb 1a ec 03 09 37 6d 2c 46 83 d1 82 68 59 1b ed b9 4a 68 39 46 b6 fe c3 0e 4a 2c d1 ab a8 a9 f4 fb ec 4d cd ec 50 b4 56 4b 7b 0b be 4e 22 fd 66 18 e8 cd 6e e5 b0 03 dd 2f d1 96 80 0c 37 fe 64 72 54 6e 9f bb 73 6d 1f 2b 86 5e ae 10 41 94 ca 59 83 6f d0 b5 52 15 b9 c8 3b e0 25 5f 1f 78 03 70 ed 02 81 80 cd 68 9a 39 64 eb f8 4d db 77 50 32 87 8a 2b d7 bd 7f 20 f1 09 0d 16 ed 57 c5 5c 85 30 70 84 72 20 a4 85 ae 35 ed d2 95 e1 d3 be e9 f3 3b be da 01 fd dd 80 ac d0 1b 45 a4 8c a4 66 db 48 fa 65 8c db fa 5b fc 34 e4 30 0d 94 91 23 33 c4 df 01 96 f0 71 5d 00 b5 b0 09 45 4e d9 04 bd b2 fe d2 ba a5 52 4e a5 70 62 b2 cb 10 4e 75 3d 67 da 00 e9 87 9b a5 36 4e 69 d2 b0
< 90 00
Going to send 255 bytes in this go.
> 10 fe 07 9a ff e7 30 24 e6 82 d0 77 03 81 80 ca 31 ff 55 3c 36 3b 22 08 32 30 da 4c 0d 9a 0f c0 da 41 23 9c 59 82 5c 2f 4a 12 10 31 04 2a d1 68 95 d4 dc 24 bf 0f 6b d3 7b 66 0e 9f e4 1a 52 a6 8c 48 10 28 94 1b af 28 a1 6f b3 64 a0 a7 5d 1d 81 e8 61 6e 78 1a 58 a7 4f d7 f3 93 2f b6 77 39 8d ed 4f 74 9a 62 bd bd 95 4f d0 bf 61 00 a3 b6 59 9e 0f c7 88 45 64 5f 63 47 56 68 a8 24 b1 e5 10 fb 9e d5 fa 7b db e9 10 24 fa 05 0a f8 a9 04 81 80 c3 39 b7 da f4 e0 91 8e ee 17 e8 51 1e 21 64 aa 17 a0 cc 5e 4a 8b f6 4e 7e 2d 46 52 10 47 e0 99 d8 0c 86 41 9d 5f fb d6 18 5c 78 07 42 f6 75 de 1e 26 7a 6f e1 cf a9 1b f7 d8 f4 28 0e 22 be 59 e6 16 ed 4c 9f d8 65 48 86 9f bd 92 07 92 05 a2 2d 23 39 9b 7b 21 33 be 9b f0 e4 b2 6c d9 c2 f7 e6 0d 5a bd 04 e0 5b ee 32 b1 bc e0 11 0c b3 56 4a 9e
< 90 00
Going to send 145 bytes in this go.
> 00 fe 07 9a 91 68 80 0d ad 59 46 b6 7c 04 76 0d e0 26 e1 05 81 80 76 f2 6f 4d 28 7c fc 75 61 09 6b 62 94 41 e0 7e 37 f6 6a b2 6d 76 61 c1 10 44 ed ca 07 12 42 17 70 c0 63 a8 e4 ab b3 16 a6 9a 7f ad cd 5a d7 8b f3 72 ef 72 84 52 19 5c 82 81 ef 53 d7 ea 61 ab af 78 ab 77 93 74 54 08 60 da 21 2f 97 cc 3a 82 d3 3e 41 48 d7 e0 0f ce 5b c3 04 7c 3c 42 96 8e 89 da 59 04 5b 4e f7 2b c4 2f e2 6e a9 9d 64 5c 96 de a9 35 b6 5b 2b 88 00 8d 9e 46 06 2e 65 88
< 90 00
Successfully imported a new private key.
Now processing for action 'import-certificate'.
Going to send 255 bytes in this go.
> 10 db 3f ff ff 5c 03 5f c1 05 53 82 03 1e 70 82 03 15 30 82 03 11 30 82 01 f9 02 14 52 0f 75 9f 7a b6 b1 2f 8c 21 4b 34 c5 32 2f b6 34 9a 6d 87 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 45 31 0b 30 09 06 03 55 04 06 13 02 41 55 31 13 30 11 06 03 55 04 08 0c 0a 53 6f 6d 65 2d 53 74 61 74 65 31 21 30 1f 06 03 55 04 0a 0c 18 49 6e 74 65 72 6e 65 74 20 57 69 64 67 69 74 73 20 50 74 79 20 4c 74 64 30 1e 17 0d 31 39 30 31 32 37 30 30 32 35 35 36 5a 17 0d 32 31 31 30 32 34 30 30 32 35 35 36 5a 30 45 31 0b 30 09 06 03 55 04 06 13 02 41 55 31 13 30 11 06 03 55 04 08 0c 0a 53 6f 6d 65 2d 53 74 61 74 65 31 21 30 1f 06 03 55 04 0a 0c 18 49 6e 74 65 72 6e 65 74 20 57 69 64 67 69 74 73 20 50 74 79 20 4c 74 64 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f
< 90 00
Going to send 255 bytes in this go.
> 10 db 3f ff ff 00 30 82 01 0a 02 82 01 01 00 be a2 c4 a1 11 ec d9 56 8c 2a e5 1d e5 e7 21 b2 6e 5b c1 32 c3 05 00 3f bb 6e f5 34 47 35 24 2b 36 2a 92 47 98 53 6a 4e 23 80 ce 7c c4 c9 0a 42 41 61 fc d0 c6 f2 c2 84 a9 25 a2 df 00 fa 8d 5b 6e 4a 7c 1e dd 37 50 28 fb 36 38 b0 47 91 b9 4a c2 10 2e 62 66 73 86 4d 41 d0 98 60 ec 24 77 2e c7 33 a1 2d 5a 6c 9f a7 f5 b7 8c 8b 96 e1 0e 58 96 75 06 43 c7 51 70 48 de a1 5e db da 0e 16 4b 9b 3f cd 56 44 00 fc 84 e7 5b f5 41 d5 7f 6b 6a 0a d1 10 e2 c1 49 a0 18 fc b9 ff e6 f8 25 60 03 f4 0a 6e 98 1b 37 5e a3 ea ee f2 aa c3 d0 78 99 f6 49 7c e4 28 44 a9 1e 5a b7 b9 db 2a 41 70 f8 ac 00 ff ea 3d 7a d8 7a d1 8d 75 75 4a ea 50 82 f5 91 1d e2 82 da 97 ad 57 47 ac 72 58 3b ba 2f 83 1d be b7 14 5d fd 81 8f 99 47 79 6b 6c 81 cc 9f 7c c5 46 c7
< 90 00
Going to send 255 bytes in this go.
> 10 db 3f ff ff 2e e7 79 7d fa 23 ab db b4 0e 2b 02 03 01 00 01 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 03 82 01 01 00 06 5a da 10 61 4d 63 a2 dd 3e 48 20 82 fb 2d dc 5e 23 d1 0f b9 3d 1d a0 a0 69 88 2c 82 33 e7 0c d2 dd c3 49 b6 c0 6a ec f6 ab 08 27 7e ad 5e ee 63 e1 f6 9c b7 fd 66 b7 85 59 3d 8c f0 07 fa d9 55 1e b4 c6 06 b7 a7 c9 8b bc ed 25 a1 f8 e7 4d 0d 67 a7 9b 96 a7 79 fb ff 72 ac e3 da f0 30 5c 5a fe 33 8a 67 4a 6b a4 c2 ef 24 6d 53 91 0a b6 2b b6 74 2a a3 9c 7e c8 95 59 fa f9 91 ab 41 78 bb 4f 74 4e f9 2d 54 0d 1b 36 ba 10 7c e4 c5 9a 55 85 81 81 db 56 e8 6c 28 d6 ee 1d 5e 92 91 1c 9d 37 b9 cc 94 6a 48 94 e5 0b 64 83 fb f0 a9 b6 99 c0 0d d2 7b d0 a3 d3 23 14 14 ee 89 aa 7b 3e b9 e5 92 59 ee b6 0d c5 ab ef a3 fe c7 bd 42 9d 89 f3 ad 33 82 10 94 52 2f ab fe
< 90 00
Going to send 42 bytes in this go.
> 00 db 3f ff 2a 31 63 27 c0 f5 69 78 20 95 64 26 37 f6 0f 4a 0c 3a c8 9c 81 50 82 bc 43 13 f3 fa 40 3c cd 01 d7 4c 0e c4 83 27 71 01 00 fe 00
< 90 00
Successfully imported a new certificate.
```

**Comment by kategray** [comment]
It looks like it may have something to do with the management pin.  Manager is just calling the piv-tool, with the command:

```
C:\PROGRA~2\Yubico\YUBIKE~1\yubico-piv-tool.exe  -r "ACS ACR33U-A1 3SAM ICC Reader ICC 0" -s 9a -K PKCS12 -a import-key --touch-policy never -k --stdin-input
```

**Comment by arekinath** [comment]
It seems that the GUI manager app tries to write a special configuration object into the applet (with tag `5FFF00`, in the same proprietary prefix that Yubico put the attestation cert). When it fails to write it, a bunch of the bits related to mgmt key derivation in the GUI app start to produce incorrect results, which is unfortunate.

I've reproduced this myself, and then also altered the applet to support storing and retrieving this configuration object at `5FFF00` and it seems to work properly after that.

It looks like the newer `ykman` (and its GUI app) also uses this same slot, so it'll help there too (though it currently doesn't let you set the reader name and also expects a bunch of other applets to be running as well as PIV, unfortunately)

**Comment by kategray** [comment]
This fixed the error with it keeping popping up the PIN dialog, but it still won't let me import.

Using a fresh install of the latest .cap:

![bug_1](https://user-images.githubusercontent.com/2415200/51809205-33a87080-226c-11e9-99b5-9fb9d2eaae30.PNG)

Attempt to import:
![bug_2](https://user-images.githubusercontent.com/2415200/51809213-58044d00-226c-11e9-895a-6e1281ca3b6a.PNG)

Test certificate, password "1234".

[testcert.zip](https://github.com/arekinath/PivApplet/files/2801014/testcert.zip)

**Comment by kategray** [comment]
Trying to hunt down what's going on here, I did a capture.  The first packets (<=8722) were launching the YubiKey PIV manager, letting it detect the card, and changing the PIN/master key (to 222222 and a derived master key from the PIN).  The later packets (>=12890) consist of attempting to load a P12 file to the card.  It's a test .p12.

I've attached both a text and a pcap capture of the process.

[capture.txt](https://github.com/arekinath/PivApplet/files/2804635/capture.txt)
[capture.zip](https://github.com/arekinath/PivApplet/files/2804645/capture.zip)

**Comment by arekinath** [comment]
It looks like over and over again throughout this it's failing to perform the admin (9b) authentication with the card. Interestingly, this is not what it does for me here (it seems to work fully from setting up PIN to importing a p12 file) -- but I'm on Linux not Windows and might have a different version of the PIV manager. Is there any chance you could get a APDU trace like that with the full data rather than "..." at the end of things? It would be useful to see the full 3DES key it actually set the admin key to and try to verify the encryption by hand.

**Comment by kategray** [comment]
The pcap file should open in Wireshark and have all the APDUs, or if you would like I can figure out a way to export the full transactions as text.

**Comment by kategray** [comment]
Looks like the pcap file is truncated by the windows usb capture driver I'm using.  I'm working on a utility to reconstruct packets from the USB analyzer I have into WireShark so I can use the CCID decoder and dump all the APDUs.

**Comment by arekinath** [comment]
Ah, sorry, thought the pcap was truncated as well, but it isn't actually in any of the packets that actually matter (just in some mostly irrelevant spots).

Looking at the admin auth attempts, it seems like the card is behaving correctly. The value for the first challenge-response pair that the host is sending (with the default admin key) looks right, then it changes the admin key, and then the auth on the new admin key looks ok as well. In the final exchange of the earlier set of packets it writes the PIVMAN file, and that succeeds. This is roughly the same as what I observe `pivman` doing to my test cards if I just go through to the main screen after setting the PIN and don't try to import any certificates or generate any keys, so that makes sense.

In the second set of APDUs (after +83 seconds) the host does successful admin auth with the card and then... stops? It doesn't send any APDUs to try to import a key or certificate, but it also doesn't receive any errors from the card. I've decrypted the challenge-response pairs there and the admin auth looks fine and using the correct key (the new one it set in the first exchange). It seems like it's not actually trying to send the key/certificate to the card.

Could it be that it's actually having trouble interpreting the `.p12` file itself? We might need to debug `pivman` rather than the card here.

FWIW I've tried with the .p12 you have in the `testcert.zip` above too on my machine and it seems to import fine. I also did a round-trip signature test afterwards and it seemed to work... so I'm a little mystified, sorry.

**Comment by arekinath** [comment]
To clarify, I don't mean that I think it's not the applet's fault (since you said it works with a real yubikey), but I'm not sure we're going to figure out what it's doing wrong from its side or the packet trace (since the application has decided not to bother trying the key import apparently)
