### ISSUE TITLE
Signature validation fails on imported certificate

### ISSUE THREAD

**Issue by kategray** [arekinath/PivApplet#17]
I have a certificate that I've imported using the command-line tool.

The cert is imported correctly, and it shows in certificate manager.  I'm able to get the public key in CAPI (for things like putty-CAC, which works fine with the certificate and a YubiKey).

When I attempt to use the certificate, the PIN prompt is successful, but the actual signature is incorrect.  Attempting to login here:

https://server.cryptomix.com/secure/

fails with ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED.  Putty-cac gives me "Server refused public-key signature despite accepting key!"

Authentication works fine, however, using a self-signed cert I created and imported the same way.

**Comment by arekinath** [comment]
I'm guessing you can't give much more detail about the certificate you imported? I've tried an imported cert+key signed by a CA I made myself against that link you provided, but it worked as well, like the self-signed case. Is it a well-known CA that issued the cert?

**Comment by kategray** [comment]
It’s a very from Comodo.  We have an account with them - if you’d like, I can include the public key and issue you a credit for the cert.  Mine works with GIDS applet, so it’s not the card.

Might importing the chain be an issue?

**Comment by arekinath** [comment]
Interesting. I did spot while looking for what could be happening here that we don't properly clear the private key slot during import and then double-check that it got initialized afterwards... I can imagine something funny going on if for example the client only sent some of the parts of the RSA key but not all of them *and* you previously had another key loaded in the slot (e.g. one generated on the card), so I'll make a separate bug to fix that up.

**Comment by kategray** [comment]
Ahh.  I've gotten in the habit now of uninstalling and reinstalling the app, so that might be it.

Is it possible to import a key in the wrong format so the proper cert is present, but the key is wrong?

**Comment by arekinath** [comment]
It's definitely possible to load a cert that doesn't match the actual key in that slot. The card applet doesn't actually parse the x509 cert (it just stores it), so there's not any real check that the public key matches the private one. From what I've seen of commercial PIV applets it's a bit hit and miss whether they do this or not (some do, some don't).

**Comment by kategray** [comment]
It's possibly the state could have been messed up due to #16 .  I was initially trying to import through there, and for some reason it breaks when I attempt to import through there (but works command line).

**Comment by kategray** [comment]
I think I might have hit upon what triggers this behaviour.

I start by doing a fresh applet install, importing the p12 using the command line above (generally to slot 9c).  I then let the GUI manager change the PIN (it's easier), and everything works.

Once I enter a single incorrect PIN, though, it fails from then on.  

![pin_entry](https://user-images.githubusercontent.com/2415200/52546365-8ca7f680-2d8c-11e9-99ae-dd463fb8a359.png)
![pin_entry_2](https://user-images.githubusercontent.com/2415200/52546367-8f0a5080-2d8c-11e9-9445-a70602898508.png)

PIN verification works, but the card does not seem to want to sign.

```
C:\Kate\JavaCard>"c:\Program Files (x86)\Yubico\YubiKey PIV Manager\yubico-piv-tool.exe" -r "Feitian SCR301 0" -averify-pin -v2
trying to connect to reader 'Feitian SCR301 0'.
> 00 a4 04 00 08 a0 00 00 05 27 20 01 01
< 6a 82
Failed selecting yk application: 6a82
> 00 a4 04 00 05 a0 00 00 03 08
< 61 34 4f 0b a0 00 00 03 08 00 00 10 00 01 00 79 0d 4f 0b a0 00 00 03 08 00 00 10 00 01 00 50 09 50 69 76 41 70 70 6c 65 74 ac 0b 80 01 03 80 01 06 80 01 07 06 00 90 00
> 00 fd 00 00 00
< 05 00 00 90 00
Action 'verify-pin' does not need authentication.
Now processing for action 'verify-pin'.
Enter PIN:
> 00 20 00 80 08 3X 3X 3X 3X 3X 3X 3X ff
< 90 00
Successfully verified PIN.
```

Card status shows PIN retries left:

```
C:\Kate\JavaCard>"c:\Program Files (x86)\Yubico\YubiKey PIV Manager\yubico-piv-tool.exe" -r "Feitian SCR301 0" -astatus
CHUID:  3019000000000000000000000000000000000000000000000000003410a77df03de5efdafa46d280993021f04b350832303530303130313e00fe00
CCC:    f015a000000116ff027fab1eb611dbbef3ac998825a059f10121f20121f300f40100f50110f600f700fa00fb00fc00fd00fe00
Slot 9c:
        Algorithm:      RSA2048
        Subject DN:     emailAddress=kgray@corecodec.com
        Issuer DN:      C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO SHA-256 Client Authentication and Secure Email CA
        Fingerprint:    133cec108f5f9c6951755d3625285bd98edb561852041adcf1c2ff8fda3efb06
        Not Before:     Jan 10 00:00:00 2017 GMT
        Not After:      Jan 10 23:59:59 2020 GMT
PIN tries left: 5
```

**Comment by kategray** [comment]
Somewhat interestingly, if I leave the PIN at the default, an invalid PIN will not trigger this behavior.

Changing the PIN with yubico-piv-tool does not trigger this behavior.  Setting a manual management PUK and key in the GUI doesn't seem to trigger it either.

**Comment by kategray** [comment]
I think this issue can likely be closed.

Loading using the CLI app seems to avoid any issues.  I've written a [guide](https://github.com/kategray/PivApplet/wiki/Smart-card-or-YubiKey-SSH-login) on using the applet, changing the PIN, etc., and I haven't been able to break it when done that way yet.
