### ISSUE TITLE
Duress PIN support

### ISSUE THREAD

**Issue by kategray** [arekinath/PivApplet#19]
Wondering if this is something that would be useful upstream.

I'm working on a fork of PivApplet, and one of the features I'm implementing is the ability to do a duress PIN.  This PIN, if used, would delete the keys immediately.

**Comment by arekinath** [comment]
Interesting idea. Are you implementing some particular spec for this, or adding your own special PIN id for managing it?

**Comment by kategray** [comment]
I haven't been able to find a PIV spec for this (though vendors seem to commonly have a duress biometric for some reason).

I worked as a Security Engineer for Honeywell; our products typically were configured to duress by adding or removing one from the last digit of the PIN (314159 -> 314150 or 314158).  That's a common approach with alarms, etc. as well.  It shouldn't be enabled by default, but is a nice option to give the user.

Now that I think about it, the PUK might be the way to go for this.  Instead of wiping the card, it would be easy enough to just lock out the regular PIN.

Activating duress mode could be as simple as changing the PUK to something like "DURESS", before changing it to the proper PUK.  That would keep compatibility with existing tools, and ensure that fat-fingering didn't result in data loss.  If the user was unaware of the PUK, then they also could not be compelled to provide it (for example, if they are in possession of the token when crossing a border).

**Comment by dengert** [comment]
Closest thing to what you want in the official PIV specs NIST sp800-73-4 (and earlier versions) is the "reset counter" is decremented when VERIFY fails and when it reaches 0 the PIN is locked. The PUK is then used to unlock. The intent is the card issuer sets the reset count and the user does not know the PUK. (I have seen cards with 3 to 10 being the value of the reset counter).

As you point out your last digit different  duress is prone to fat fingering. With or without the duress code the reset counter can be abused by entering multiple wrong PINs to lock the card.

**Comment by kategray** [comment]
"With or without the duress code the reset counter can be abused by entering multiple wrong PINs to lock the card."

Yes, though it does get to be a lot more obvious when you do that.

**Comment by kategray** [comment]
I'm going to go ahead and close this.
