### ISSUE TITLE
macOs does not recognize the Piv smartcard

### ISSUE THREAD

**Issue by Grivus** [arekinath/PivApplet#23]
I'm still trying to get things up on macOS, and met another problem: Piv applet is running, but macOS can't see any smartcard connected.

I followed the readme and my configuration now is:

- vsmartcard for emulating smart card reader (readers are displayed for both pcsctest and opensc-tool -l)
- jcardsim and PivApplet installed & running (I've executed all relevant commands from readme in terminal and got the same result, as described there)

The problem is, when I try the 
`security smartcards-list`
or 
`system_profiler SPSmartCardsDataType`

there are no smartcards from their point of view:
`No smartcards found `
and empty 
`Available SmartCards (keychain):`
`Available SmartCards (token):`

In Keychain app the new keychain appears, named PIV_II, but it stays empty for some reason. 

Any guesses, what am I'm doing wrong?

**Comment by darconeous** [comment]
I think you meant `security list-smartcards`.

In any case, have you added any certificates to the app? That might make it work properly.

If it is showing up in the keychain then you likely have the OpenSC tokend extension installed. That might interfere with the new macOS secure token system.

**Comment by darconeous** [comment]
It seems to work for me once I load a key.

**Comment by arekinath** [comment]
It sounds like this was a lack of keys/certs on the card causing it to not come up. If it wasn't, please reopen.
