### ISSUE TITLE
GENERATE ASYMMETRIC KEY PAIR for ECC Keys adds extra byte

### ISSUE THREAD

**Issue by dengert** [arekinath/PivApplet#30]
See: https://github.com/OpenSC/OpenSC/issues/2028#issuecomment-627579440

The response is not the same as from a real NIST PIV card. This may cause problems with Yubico-piv-tool.

**Comment by arekinath** [comment]
Ah yes, I see. It's calling `wtlv.push256()` instead of getting the real length so it can guarantee it's DER. Part of the changes for P-384 support. I'll get it fixed up, sorry.

**Comment by Jakuje** [comment]
The current master works fine. Thanks.
