### ISSUE TITLE
Trouble shooting

### ISSUE THREAD

**Issue by jasonkolodziej** [arekinath/PivApplet#40]
Good evening,

I am trying to go through using the Yubico `ykman` tool with this applet. I am just checking to make sure that it is supported??

## Setup
A PIVKey C910
"The PIVKey C910 Smart Card is based on the Infineon SLE 77 Chip and the Feitian Java Card OS. This platform is FIPS 140-2 Level 3 validated, CMVP #2470."
From what I can tell the GlobalPlatform is v2.1.1 and the OS Java Card v2.2.2

After using the `gp` tool I followed instructions per the ReadME.md

using `PivApplet-0.8.2-jc222-RESA.cap` release.

The trickiest part was trying to get `yubico-piv-tool` to see the card. I had notice a lot of people were using a USB Smartcard Reader. Not 100% sure if these were "external"... But my reader is a Broadcom **internal** SCR.

i.e. `yubico-piv-tool -r Broadcom -a generate -s 9e`

I have accomplished setting up Card Authentication as well as Key Management (9e, 9d; respectively).

However when wanting to use the ykman tool (preferably wanted the GUI, but I would need to rebuild the program to seek `-r Broadcom`) I keep getting

``` 
ykman -r Broadcom piv info

...

No yubikey found. #not the exact error because I do not have it up on my screen
```

Could someone verify if I actually need to go Rebuild the Applet for said card? or is the is `ykman` tool issue?

Any thoughts, any guesses?

**Comment by dengert** [comment]
So you are asking this question on the arekinath/PivApplet  but not using the applet? 

And you are trying to initialize a PIVKey C910 card from Taglio? 
They have thier own tools https://pivkey.zendesk.com/hc/en-us/categories/200284639-Technical-Support which might be easier. 

The yubikey devices have their own built in readers and the yubico tools may use for specific yubico instructions that may not work with the PIVKey. 

NIST sp800-73-4 defines PIV and left it up to card vendors to define how to initialize the cards. 

The OpenSC piv-tool can also be used with some cards, but you may need to know special card commands and admin keys as defined in the vendors documents.

**Comment by jasonkolodziej** [comment]
@dengert I am using this repos applet. The cards I purchased were not locked so I removed their applet and install this repos on there.

 http://smartcard-atr.appspot.com/parse?ATR=3BFC180000813180459067464A00641606F2727E00E0

**Comment by jasonkolodziej** [comment]
I should state though the OS is a certain type of Java OS (Feitian Java Card OS) which I don't really understand... other than the fact that is makes it a tad more difficult to resolve version dependencies. Also I can talk to the card perfectly fine using the `yubico-piv-tool` just not the yubico's `ykman` tool. I am just trying to figure out is this a 1. Applet build issue 2. other people are having the same issue with getting their card recognized by the `ykman` executable.

Thanks! :-)

**Comment by dengert** [comment]
Yubikeys can have more then a PIV applet. [ykman](https://developers.yubico.com/yubikey-manager/) deals with managing the other yubico applets: OpenPGP, Fido, Oauth, OTP on the Yubikey devices. I would not expect ykman to work on a device that is not from Yubico.
