### ISSUE TITLE
Only Slot 9e can use?

### ISSUE THREAD

**Issue by cnZary** [arekinath/PivApplet#46]
I'm trying to import/Generation some ECCP256/RSA2048 key to 9a/9c/9e in J3H145 card running the PivApplet-0.8.2-jc304-REePSAx.cap
But these slots are not available
only 9e can use

**Comment by arekinath** [comment]
Was this over contactless? The `PIV_STRICT_CONTACTLESS` build option (`S` in the feature string there) blocks everything except `9e` over contactless (since the PIV spec says to do this unless you support SM). The next version will have some more pre-built CAP files without this flag set.

**Comment by cnZary** [comment]
Yes im use ACR122U over contactless,but i try to set build.xml PIV_STRICT_CONTACTLESS to false,But still unavailable(0.8.2)
But it works in 0.9.0(use ant make)
Thanks~
