### ISSUE TITLE
Implement MultiSelectable 

### ISSUE THREAD

**Issue by koh-osug** [arekinath/PivApplet#49]
I'm running into an issue when using in an environment where the card cannot be reset. After opening a logical channel the card is selected and re-selection of the applet throws an error SW 6985. Because I cannot reset the card I have to restart the whole device which is prohibitive because the other applications can then also not access the card anymore. Maybe the implementation also has an issue with closing the channel correctly.
What would be the side effects of being multi-selectable? In my case I'm the only application accessing it, but are there structures which could be damaged when executing commands interleaved on different logical channels?

**Comment by arekinath** [comment]
I'm not sure the PIV specs talk about multi-channel usage at all. I haven't been able to find anything with a quick search, but it does explicitly list all of the PIV commands with `CLA=00` (which implies to me they are only ever accepted on the default channel). Most commercial PIV applets I can find by googling around don't support MultiSelectable, either.

If this applet was to support this, I'm pretty sure it would be considered a proprietary extension from the perspective of the PIV standard.

I would imagine that all of the currently "global" transient state (like key usage criteria states, PIN entry etc) would have to be separated out on a per-logical-channel basis for this to work sensibly. We would basically have to treat each channel as a separate instance of the applet which happened to share PINs and keys with each other. That would require a lot of revision to the code.

**Comment by kaoh** [comment]
OK, thanks. If I need I will just add the MultiSelect interface to make it work, I use only one application accessing the applet and will not run into issues. This can be closed.
