### ISSUE TITLE
Remove limits on chained APDU and cert sizes

### ISSUE THREAD

**Issue by arekinath** [arekinath/PivApplet#6]
The applet should be able to deal with arbitrarily large chains of APDUs (currently it's limited by the RAM_BUF size) and certificates, up to the memory limits of the card platform it's running on.

This probably means using multiple buffers dynamically and falling back to EEPROM if transient RAM can't be acquired.

**Comment by dengert** [comment]
The TLV of an object contains the size of the full object, so you use that to dynamically allocate a large buffer.

**Comment by martinpaljak** [comment]
JavaCard is not a "dynamic" platform, so resource allocation on the fly is not a good idea, if possible to avoid.

**Comment by dengert** [comment]
NIST 800-73 does not talk about extended APDUs. But it does use command chaining and get response for large transfers in any commands that may need it. 

The PUT DATA command  is only used during initialization and provisioning. So what I am suggesting is the card accepts the first block of the chain, looks at the BER-TLV of the data to determine the size of the full object. It can then do whatever java requires to allocate space for the object before receiving the remainder of the object.     

I am not a Java Card expert. Are command chaining and get response handled by the applet or by Java?

**Comment by arekinath** [comment]
So what I've just pushed into master is an implementation of scatter-gather lists for buffering APDUs. Basically, we can allocate multiple chunks (512 bytes or 256 bytes if those aren't available) and spread the data across them, and then if we're going to store something in EEPROM, reassemble the data into the EEPROM buffer across chunk boundaries as needed. We re-use the chunks between exchanges so that we avoid depending on GC being available on the card (on a card without GC we will end up using as much memory as we needed for the largest APDU you ever sent/received, but no more).

I've tested this on my J3D081 cards up to 8kb for now (they seem happy to allocate that much entirely in RAM if it's in 512 byte chunks) -- can lift that higher later by increasing the max number of chunks.

**Comment by arekinath** [comment]
J3D081 test results:

```
chunk 0: 0x200 transient
chunk 1: 0x200 transient
chunk 2: 0x200 transient
chunk 3: 0x200 transient
chunk 4: 0x100 transient
chunk 5: 0x400
chunk 6: 0x400
chunk 7: 0x400
chunk 8: 0x400
...
chunk 15: 0x400
```

So it actually ran out of transient memory (RAM) after 2304 bytes and is using EEPROM for everything after that, for a total max APDU chain length of 13568 bytes.

**Comment by frankmorgner** [comment]
While your implementation is fun to read, I agree with @martinpaljak that the implementations I've seen assume hard limits for simplicity and for security. (ISO 7816 even defines capabilities for announcing send/receive limits)

**Comment by arekinath** [comment]
I've found though that on most cards you really can't allocate more than about 900-1000 bytes in a single transient byte array. 1k is really not big enough for a lot of certs, and the hash-on-card extension we support in PivApplet means you also are limited to signing only <1k things with ECDSA with using that size block as a buffer. So I do think it's a good idea for this applet to be able to handle larger APDUs in some way (at least a couple of K).

The other option to SGList I can see would be to make a streaming TLV parser that doesn't need to buffer it all up (feed it into the signer or EEPROM buffer as the APDU chunks arrive), but it does make doing length checks and assertions (and a bunch of other stuff there) simpler having all the data buffered in at once. I'm not sure the TX side of that could be much simpler than the SGList, either -- it would still have to track more than one buffer position. I don't know if overall the code for streaming TLV would be that much simpler than the SGList implementation (which can still be cleaned up/simplified a fair bit).

You think continuing with the SGList code is a bad enough idea to have a go at the other way?

**Comment by arekinath** [comment]
FWIW I was thinking of refactoring the SGList code into two parts -- one for allocating and tracking the chunks of memory on an ongoing basis, and another for the "virtual buffer" made out of the set of them (reading and writing, the rptr and wptr etc). The `steal()` function and friends are the hairiest bit of it imho and would go away by separating those two functions.
